" How many lines of history VIM has to remember
set history=100

" Filetype plugins
filetype plugin on
filetype indent on

" Set to auto read when a file is changed from outside
set autoread
au FocusGained,BufEnter * checktime

" Graphical menu for autocomplete
set wildmenu

" Make 'find' fuzzy
" Search down into subfolders
" Provides tab completion for all file related tasks
set path+=**

" Always show cursor position
set ruler

" Configure backspace to work properly in INSERT mode
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Highlight search results
set hlsearch
set incsearch

" Enable syntax highlighting
syntax enable              

" Use solarized color scheme
colorscheme badwolf

" Use spaces for tabs
set expandtab

" TAB = 4 spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Set an hybrid of absolute and relative numbers
set number relativenumber 

" Highlight matching
set showmatch

" Shows the last command in the bottom right
set showcmd

" Draws a horizontal highlight on the line the cursor is currently on
set cursorline

" Set vertical split to open new window on the right
set splitright

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader=","

" Map ,<space> to clear search highlight
nnoremap <leader><space> :nohlsearch<CR>

" Map ,ss to toggle and untoggle spell checking
map <leader>ss :setlocal spell!<CR>

" Map ,t to open a new tab
map <leader>t :tabnew<CR>

" Map ,g to perform vimgrep recursively
map <leader>g :vimgrep  **/*<left><left><left><left><left>

" Map ,/ to perform a 'comment block' command (using //)
map <leader>/ :normal 0i//<CR>

" Use CSyntaxAfter plugin for syntax highlight on C-like languages
autocmd! FileType c,cpp,java,php call CSyntaxAfter()

" Set highlight at 101th column for informative purposes
" For git commit, highlight the 72th column
let &colorcolumn="101"
autocmd FileType gitcommit let &colorcolumn="72"
